SELECT HUB.HUB_CUSTOMER_KEY AS DIM1_CUSTOMER_KEY,
	HUB.CUSTOMER_NUMBER,
	SAT.FIRST_NAME,
	SAT.LAST_NAME,

FROM HUB_CUSTOMER HUB, SAT_CUSTOMER_DETAILS SAT

WHERE HUB.CUSTOMER_NUMBER = SAT.CUSTOMER_NUMBER

AND SAT.LOAD_DTS = 
(
    SELECT MAX(SAT2.LOAD_DTS)
    FROM SAT_CUSTOMER_NAME SAT2
    WHERE HUB.CUSTOMER_NUMBER = SAT2.CUSTOMER_NUMBER
)